"""empty message

Revision ID: 00dbbeba87b2
Revises: 
Create Date: 2025-05-28 09:06:10.321099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dbbeba87b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=100), nullable=False),
    sa.Column('Telefone', sa.String(length=20), nullable=True),
    sa.Column('Cpf', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Quarto',
    sa.Column('Nro', sa.Integer(), nullable=False),
    sa.Column('Preco', sa.Float(), nullable=False),
    sa.Column('Descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Nro')
    )
    op.create_table('Status',
    sa.Column('Nome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Nome')
    )
    op.create_table('Data',
    sa.Column('Data', sa.Date(), nullable=False),
    sa.Column('Nro_quarto', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Nro_quarto'], ['Quarto.Nro'], ),
    sa.ForeignKeyConstraint(['Status'], ['Status.Nome'], ),
    sa.PrimaryKeyConstraint('Data', 'Nro_quarto')
    )
    op.create_table('Reserva',
    sa.Column('Nro', sa.Integer(), nullable=False),
    sa.Column('Nome_status', sa.String(length=20), nullable=True),
    sa.Column('Data_inicio_data', sa.Date(), nullable=True),
    sa.Column('Numero_quarto_data_inicio', sa.Integer(), nullable=True),
    sa.Column('Data_fim_data', sa.Date(), nullable=True),
    sa.Column('Nro_quarto_data_fim', sa.Integer(), nullable=True),
    sa.Column('Data', sa.Date(), nullable=True),
    sa.Column('Id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Data_fim_data', 'Nro_quarto_data_fim'], ['Data.Data', 'Data.Nro_quarto'], ),
    sa.ForeignKeyConstraint(['Data_inicio_data', 'Numero_quarto_data_inicio'], ['Data.Data', 'Data.Nro_quarto'], ),
    sa.PrimaryKeyConstraint('Nro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reserva')
    op.drop_table('Data')
    op.drop_table('Status')
    op.drop_table('Quarto')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
